---
# tasks file for roles/web-server
- name: Install pip packages
  pip:
    name: "{{ pip_packages }}"
    state: latest

- name: Install Apache
  apt:
    name: apache2
    state: latest

- name: Ensure Apache starts
  service:
    name: apache2
    state: started
    enabled: yes