- hosts: localhost
  tasks:
  - name: Attempt to fetch API keys
    uri:
      url: http://rancherctl.mybytesni.com/v1/apikeys
      methods: GET
      status_code: 200
    register: api

  - name: Create API keys
    uri:
      url: http://rancherctl.mybytesni.com/v1/apikeys
      body: {"name" : "main", "description": "main key"}
      body_format: json
      method: POST
      status_code: 201
    register: key
    when: api['json']['data'] == []

  # - name: Add Github authentication