---
# handlers file for roles/supervisor

- name: Include applications supervisor config
  shell: printf "\n[include]\nfiles=conf.d/*.conf" >> /etc/supervisor/supervisord.conf

- name: Restart supervisor
  systemd:
    name: supervisord
    state: restarted
    daemon_reload: yes