---
# tasks file for roles/rancher-container-host

- name: Install pip packages
  pip:
    name: "{{ pip_packages }}"
    state: latest
    executable: pip3

- name: Copy provisioning script
  template:
    src: provisioner.py
    dest: /usr/local/lib/provisioner.py
    owner: root
    group: root
    mode: 0770

- name: Run provisioning script
  shell: python3 /usr/local/lib/provisioner.py http://rancherctl.mybytesni.com v1.2.11
  when: not amibuilder